### ISSUE TITLE
Any plans for the 1.5.12 release?

### ISSUE THREAD

**Issue by blueberry** [bytedeco/javacpp-presets#1620]
@saudet I don't mean to bug you, but is there any timeline for 1.5.12 (javacpp and javacpp-presets)? There were some important updates since 1.5.11, and I guess the average 6-ish months release cycle is around the corner...

This is not a roadblock, of course, as anyone can pin the snapshots, but this requires users downstream to know that they need to set the snapshot repository in their projects.

It's fine if you don't want to do that soon, it's just that some information would help to know what to expect in the coming weeks/months and plan accordingly.

**Comment by saudet** [comment]
Sometime this year, but if all you want are updates to 1.5.11 I could give you access to publish for org.bytedeco.

**Comment by blueberry** [comment]
I use some 1.5.12 stuff (both javacpp and a few presets)...

**Comment by saudet** [comment]
Right, it might be a good idea to make a release before OSSRH shuts down too. Who knows what's going to happen after that

**Comment by mullerhai** [comment]
> Right, it might be a good idea to make a release before OSSRH shuts down too. Who knows what's going to happen after that

right, please  consider bring kaldi   to javacpp, thanks https://github.com/bytedeco/javacpp-presets/issues/1617 and open3d  nccl

**Comment by blueberry** [comment]
> Right, it might be a good idea to make a release before OSSRH shuts down too. Who knows what's going to happen after that

I don't know how much manual work there is in a proper release vs snapshots, but it that's possible, I think more frequent releases of the presets would only benefit the visibility and stability of JavaCPP presets. Or, perhaps, some sort of decoupling of the releases of various presets form the javacpp itself, and between each other. For example, if JavaCPP is very stable at 1.X.Y, maybe the projects would bump their versions independently when the upstream version is updated and the javacpp integration tested for a while. For example, javacpp cuda would go from 12.6-9.5-1.5.12 -> 12.8-9.5.-1.5.12-SNAPSHOT -> 12.8-9.5-12.8. So the snapshot would not be related to javacpp, but to javacpp-cuda, for most cases (presets updates). The current scheme would also work, as javacpp bump to 1.5.13-SNAPSHOT would bump to 12.6-9.5-1.5.13-SNAPSHOT, and proceed with snapshots until the javacpp 1.5.13 is released...

**Comment by blueberry** [comment]
The current situation is that 50 projects of very complex dependency structure have to be moved in unison, which is very difficult I suppose.

**Comment by saudet** [comment]
I can't get OpenCV  to build with CUDA 12.9 on Windows, so I guess I'll wait until that gets fixed before making a release

**Comment by blueberry** [comment]
Judging by the latest github actions report, the OpenCV and PyTorch issues on Windows are resolved, or we're not quite there?

**Comment by mullerhai** [comment]
> Judging by the latest github actions report, the OpenCV and PyTorch issues on Windows are resolved, or we're not quite there?

really ,if pytorch libtorch have some big upgrade ,storch will update the version

**Comment by saudet** [comment]
CUDA 12.9 is still unable to build OpenCV and PyTorch on Windows. I guess they're going to fix that in 12.9.1 or something

**Comment by blueberry** [comment]
Thanks Samuel. I didn't realize that it's an upstream problem. I thought the issue was related to something in JavaCPP's build.

I wanted to explore more about it, but I couldn't find relevant information, other than PyTorch 2.7 requires 12.8 (https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix). Other sources suggest that on windows, it's even much earlier version of CUDA that is mandatory, but I couldn't confirm that in official sources. https://pytorch.org/get-started/locally/ refers to 12.8 on Windows (but it also suggests 12.8 on Linux). Now I'm confused...

**Comment by saudet** [comment]
Still broken with CUDA 12.9.1 🤦

**Comment by saudet** [comment]
Done! Enjoy

**Comment by blueberry** [comment]
Thank you!

**Comment by mullerhai** [comment]
good done ,Thanks
