### ISSUE TITLE
Missing jnimxnet.dll in windows-x86_64.jar coming from the maven repository

### ISSUE THREAD

**Issue by Neiko2002** [bytedeco/javacpp-presets#234]
Congratulation to the 1.2 release. I've read the changelog and was happy to find the new MXNet preset. Running the ImageClassificationPredict example on OSX was straightforward as usual, but when I tried it on windows I got the following exception:
UnsatisfiedLinkError: no jnimxnet in java.library.path

The windows-x86_64.jar coming from Maven seems to be empty:
[http://search.maven.org/remotecontent?filepath=org/bytedeco/javacpp-presets/mxnet/master-1.2/mxnet-master-1.2-windows-x86_64.jar](url)

**Comment by saudet** [comment]
Yep, it's missing. Would you like to contribute the bit that is missing from the cppbuild.sh script?

**Comment by Neiko2002** [comment]
I'm working on it right now. The first strange thing I found was after opening the "VS2013 x86 Native Tools Command Prompt" and calling "mvn clean install" in the javacpp directory, I got two Java Out-of-Memory-Exceptions for the testLongIndexer and the testDoubleIndexer test. Removing them solved the problem and resulted in a successful build so far.

**Comment by Neiko2002** [comment]
Next thing, in the "Build Environments" Wiki you might want to add "tar", "make" and "patch" to the tools needed to build some of the presets:
pacman -S base-devel tar patch make ...

**Comment by saudet** [comment]
Testing JavaCPP on 32-bit platforms will results in errors like that, but very few developers don't have access to 64-bit machines anyway, so I'm not sure it's something worth worrying about.

**Comment by Neiko2002** [comment]
This also happens on a 64-bit windows platform using the "VS2013 x64 Native Tools Command Prompt" &#10132; "c:\msys64\mingw64_shell.bat" command line. But like I said the problem only occurs with javacpp 1.2.1, the current 1.2 is fine.

**Comment by Neiko2002** [comment]
The commit c731d1d worked. I do get the OutOfMemoryErrors but the build does not crash because of it.  But there is a potential other problem. For all test*Pointer tests a get the same error:

```
testIntPointer(org.bytedeco.javacpp.PointerTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: expected:<7622623231> but was:<7622623232>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.bytedeco.javacpp.PointerTest.testIntPointer(PointerTest.java:272)
```

**Comment by saudet** [comment]
Please try again with the current HEAD.

**Comment by Neiko2002** [comment]
I do get the same error.

**Comment by saudet** [comment]
Right, I see how that might happen. Let me check how to fix that...

**Comment by saudet** [comment]
This commit should fix that: https://github.com/bytedeco/javacpp/commit/8a7b271b6c8b50af216c22eca5350d951a26cca5

**Comment by Neiko2002** [comment]
It does work. I will close this issue now. We still have the pull request to communicate.
