### ISSUE TITLE
FloatSolverRegistry.CreateSolver(solverParam) can switch between GPU and cpu during running?

### ISSUE THREAD

**Issue by nhe150** [bytedeco/javacpp-presets#255]
1) code:
Caffe.set_mode(Caffe.GPU)
Caffe.SetDevice(gpuId)
FloatSolverRegistry.CreateSolver(solverParam)

2) after running for some time: Notice GPU utilization is zero, CPU getting busy. 40 loops iteration went from 52 seconds to 1 hour or even longer. 
This suggest or hint the switching is happened as we suspect.
Donot know for sure. Will provide more evidence.

3) How do javacpp preset caffe or even caffe determine to use GPU or cpu?

4) using lmdb for solver.prototxt running googlenet.  --- extra reader.cpp  point to consider also.

**Comment by saudet** [comment]
I'm afraid that is specific to Caffe, so it's probably a bug in Caffe. The latest release (rc3) is getting old, so maybe it's been fixed and updating the latest in the master branch would help?

**Comment by nhe150** [comment]
I and my colleges conclude the GPU switching to cpu is indeed the case happening automatically. 

We would like to build the javacpp preset caffe libraray in Ubuntu 14.04. Do you have the instruction how to build with cuda support?

**Comment by nhe150** [comment]
Thank you for the good suggestion also :)

**Comment by nhe150** [comment]
If someone could provide a ubuntu 14.04  javacpp preset with cuda build docker images, it will speed up the process of find this bug.

**Comment by saudet** [comment]
This should work:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#linux-x86-and-x86_64

**Comment by nhe150** [comment]
Thank you for quick response. Will the centos 7 docker build version work on Ubuntu? Just to confirm.

**Comment by saudet** [comment]
Yes, it will work. Let's try to confirm it's a bug in Caffe before we rule out that it isn't a problem with JavaCPP :)

**Comment by nhe150** [comment]
I notice this switching quite often now. I have no idea how this can happen. I also notice, you call caffeNet.step(1) , the GPU to cpu switching may happen immediately. :)

**Comment by nhe150** [comment]
I am switching to tensor flow now because the frustration of GPU to cpu switching. :)

**Comment by saudet** [comment]
I've just released an update based on the current master branch. It has version "master-1.2":
https://github.com/bytedeco/javacpp-presets/tree/master/caffe
http://search.maven.org/#search%7Cga%7C1%7Cbytedeco%20caffe
Give it a try. Maybe it's an issue they have since fixed.

**Comment by nhe150** [comment]
Thank you very much.

**Comment by nhe150** [comment]
I have tried  master-1.2.  GPU switch to cpu in the middle of training is still happening.
